POST http://localhost:3001/account/register
Content-Type: application/json

{
    "username": "testuser",
    "password": "Qwerty123"
}

###
DELETE http://localhost:3001/account/manage
Content-Type: application/json

{
    "username": "testuser",
    "password": "Qwerty123"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "Qwerty123"
}

###
POST http://localhost:3001/auth/logout
Authorization: Bearer INSERT_TOKEN_HERE

###
GET http://localhost:3001/sessions
Content-Type: application/json

{
    "month": "2022-06"
}

###
GET http://localhost:3001/sessions?month=2022-06

###
POST http://localhost:3001/session/reserve
Authorization: Bearer INSERT_TOKEN_HERE
Content-Type: application/json

{
    "dateFrom": "2022-06-09:16:00",
    "dateTo": "2022-06-09:17:00"
}

###
DELETE http://localhost:3001/session/reserve
Authorization: Bearer INSERT_TOKEN_HERE
Content-Type: application/json

{
    "id": "62970803bc4f7d858717d4ba"
}